apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http
      port: 9093
      targetPort: http
      nodePort: 30093
      protocol: TCP
