apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: hras-system
data:
  ollama_base_url: "http://host.docker.internal:11434"
  ollama_model: "nemotron-3-nano:30b-cloud"
  ollama_embedding_model: "nomic-embed-text"
  chroma_persist_directory: "/data/chroma_db"
  api_url: "http://backend-service.hras-system.svc.cluster.local:8000"
  database_url: "postgresql+asyncpg://hras:hras_dev_password@postgres.default.svc.cluster.local:5432/hras"
  use_postgres: "true"
