apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hras-system

resources:
  - ../../base/postgres/
  - ./dev-postgres-secret.yaml

patches:
  - path: ./dev-postgres-patch-service.yaml
