apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hras-production

resources:
  - ../../base/backend
  - configmap.yaml

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml

images:
  - name: backend-image
    newName: ghcr.io/OWNER/hras-backend
    newTag: "latest"
  - name: ingest-image
    newName: ghcr.io/OWNER/hras-backend
    newTag: "latest"

commonLabels:
  environment: production
  app.kubernetes.io/part-of: hras
