apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: hras-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: backend
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
