apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/frontend

patchesStrategicMerge:
  - prod-frontend-patch-deploy.yaml
  - prod-frontend-patch-service.yaml

images:
  - name: frontend-image
    newName: your-registry.com/hras-frontend
    newTag: v0.2.0

namespace: hras-production

commonLabels:
  environment: production
  version: v0.2.0
