apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - prometheus-rbac.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - alertmanager-config.yaml
  - alertmanager-deployment.yaml
  - grafana-deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: hras-monitoring
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
