apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/monitoring

patches:
  - path: dev-monitoring-patch-prometheus.yaml
  - path: dev-monitoring-patch-grafana.yaml
  - path: dev-monitoring-patch-alertmanager.yaml
