apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: hras-system
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: serviceaccount

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: hras-system
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: hras-system
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: rbac
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: hras-system
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
