apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: hras-system
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"

spec:
  selector:
    app: backend
  ports:
    - name: api
      port: 80
      targetPort: api
      protocol: TCP
    - name: metrics
      port: 8000
      targetPort: metrics
      protocol: TCP
